Web/BI/BI/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BI.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

Web/PCS2044/urls.py
from django.conf.urls import patterns, include, url
from tastypie.api import Api
from api import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    #URLS de Entregadores
    #url(r'^entregadores/novo$','rh.views.create_funcionario'),
    #url(r'^entregadores/editar/(?P<funcionario_id>[0-9]+)/$','rh.views.edit_funcionario'),
    url(r'^entregadores/mapa/(?P<funcionario_id>[0-9]+)/$','rh.views.funcionario_detail'),
    #url(r'^entregadores/deletar/(?P<funcionario_id>[0-9]+)/$','rh.views.delete_funcionario'),
    #url(r'^entregadores/$','rh.views.index'),
    
    #url(r'^clustering/$','pedido.views.clustering'),
    #URLS paginas estaticas
    url(r'^', include('staticPages.urls', namespace="staticPages")),
    url(r'^financeiro/', include('financeiro.urls')),
    url(r'^rh/', include('rh.urls')),
    url(r'^estoque/', include('estoque.urls')),
    url(r'^cardapio/', include('cardapio.urls')),
    url(r'^promocao/', include('promocao.urls')),
    url(r'entrega/', include('entrega.urls')),
    url(r'pedido/', include('pedido.urls')),

    
    #URLS login
    #url(r'^login/(?P<data=>$)', 'login.views.login'),
    url(r'^login$', 'login.views.login'),
    url(r'^logout', 'login.views.logout'),
    # Examples:
    # url(r'^$', 'PCS2044.views.home', name='home'),
    # url(r'^PCS2044/', include('PCS2044.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^novo_pedido/','orderGrouping.views.create_order'),
)

Web/cardapio/urls.py
from django.conf.urls import patterns, include, url
from cardapio import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^pizza$', views.pizza, name='pizza'),
	url(r'^bebida$', views.bebida, name='bebida'),
	url(r'^ingrediente$', views.ingrediente, name='ingrediente'),
	url(r'^ingrediente/novo$', views.ingredienteNovo, name='ingredienteNovo'),
	url(r'^ingrediente/consulta$', views.ingredienteConsulta, name='ingredienteConsulta'),
	url(r'^ingrediente/cadastrar$', views.ingredienteCadastrar, name='ingredienteCadastrar'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)/editar$', views.ingredienteEdita, name='ingredienteEdita'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)/alterar$', views.ingredienteAltera, name='ingredienteAltera'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)$', views.ingredienteDados, name='ingredienteDados'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)/deletar$', views.ingredienteDeletar, name='ingredienteDeletar'),
	url(r'^pizza/nova$', views.pizzaNova, name='pizzaNova'),
	url(r'^pizza/consulta$', views.pizzaConsulta, name='pizzaConsulta'),
	url(r'^pizza/cadastrar$', views.pizzaCadastrar, name='pizzaCadastrar'),
	url(r'^pizza/(?P<pizza_id>\d+)$', views.pizzaDados, name='pizzaDados'),
	url(r'^pizza/(?P<pizza_id>\d+)/editar$', views.pizzaEdita, name='pizzaEdita'),
	url(r'^pizza/(?P<pizza_id>\d+)/alterar$', views.pizzaAltera, name='pizzaAltera'),
	url(r'^pizza/(?P<pizza_id>\d+)/ingredienteDaPizza$', views.pizzaIngrediente, name='pizzaIngrediente'),
	url(r'^pizza/(?P<pizza_id>\d+)/adicionar$', views.pizzaIngredienteAdiciona, name='pizzaIngredienteAdiciona'),
	url(r'^pizza/(?P<pizza_id>\d+)/deletar$', views.pizzaDeletar, name='pizzaDeletar'),
	url(r'^pizza/(?P<pizza_id>\d+)/(?P<pizzaingrediente_id>\d+)/deletarIngrediente$', views.pizzaDeletarIngrediente, name='pizzaDeletarIngrediente'),
	url(r'^bebida/nova$', views.bebidaNova, name='bebidaNova'),
	url(r'^bebida/consulta$', views.bebidaConsulta, name='bebidaConsulta'),
	url(r'^bebida/cadastrar$', views.bebidaCadastrar, name='bebidaCadastrar'),
	url(r'^bebida/(?P<bebida_id>\d+)$', views.bebidaDados, name='bebidaDados'),
	url(r'^bebida/(?P<bebida_id>\d+)/editar$', views.bebidaEdita, name='bebidaEdita'),
	url(r'^bebida/(?P<bebida_id>\d+)/alterar$', views.bebidaAltera, name='bebidaAltera'),
	url(r'^bebida/(?P<bebida_id>\d+)/deletar$', views.bebidaDeletar, name='bebidaDeletar'),
	url(r'^lista$', views.listaProduto, name='lista'),
)

Web/rh/urls.py
from django.conf.urls import patterns, include, url
from rh.views import *
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="../templates/index_rh.html"), name="index_rh"),
    url(r'^funcionarios/lista_funcionarios/$', FuncionarioList.as_view(), name='funcionarios_list') ,
    url(r'^funcionarios/cria_funcionario/$', FuncionarioCreate.as_view(), name='funcionario_create'),
    url(r'^funcionarios/edita_funcionario/(?P<pk>\d+)$', FuncionarioUpdate.as_view(), name='funcionario_update'),
    url(r'^funcionarios/remove_funcionario/(?P<pk>\d+)$', FuncionarioDelete.as_view(), name='funcionario_delete'),
    url(r'^funcionarios/detalha_funcionario/(?P<pk>\d+)$', FuncionarioDetail.as_view(), name='funcionario_detail'),

    url(r'^folhaPagamento/$', FolhaPagamento.as_view(), name='folha_pagamento') ,

    url(r'^cargos/lista_cargos/$', CargoList.as_view(), name='cargos_list') ,
    url(r'^cargos/cria_cargo/$', CargoCreate.as_view(), name='cargo_create'),
    url(r'^cargos/edita_cargo/(?P<pk>\d+)$', CargoUpdate.as_view(), name='cargo_update'),
    url(r'^cargos/remove_cargo/(?P<pk>\d+)$', CargoDelete.as_view(), name='cargo_delete'),
    url(r'^cargos/detalha_cargo/(?P<pk>\d+)$', CargoDetail.as_view(), name='cargo_detail'),

    url(r'^contratos/lista_contratos/$', ContratoList.as_view(), name='contratos_list') ,
    url(r'^contratos/cria_contrato/$', ContratoCreate.as_view(), name='contrato_create'),
    url(r'^contratos/edita_contrato/(?P<pk>\d+)$', ContratoUpdate.as_view(), name='contrato_update'),
    url(r'^contratos/remove_contrato/(?P<pk>\d+)$', ContratoDelete.as_view(), name='contrato_delete'),
    url(r'^contratos/detalha_contrato/(?P<pk>\d+)$', ContratoDetail.as_view(), name='contrato_detail'),
    url(r'^contratos/demissao_contrato/(?P<pk>\d+)$', ContratoUpdateParaDemissao.as_view(), name='contrato_demissao'),

    url(r'^ferias/lista_ferias/$', FeriasList.as_view(), name='ferias_list') ,
    url(r'^ferias/cria_ferias/$', FeriasCreate.as_view(), name='ferias_create'),
    url(r'^ferias/edita_ferias/(?P<pk>\d+)$', FeriasUpdate.as_view(), name='ferias_update'),
    url(r'^ferias/remove_ferias/(?P<pk>\d+)$', FeriasDelete.as_view(), name='ferias_delete'),
    url(r'^ferias/detalha_ferias/(?P<pk>\d+)$', FeriasDetail.as_view(), name='ferias_detail'),

    url(r'^licencas/lista_licencas/$', LicencasList.as_view(), name='licencas_list') ,
    url(r'^licencas/cria_licencas/$', LicencasCreate.as_view(), name='licencas_create'),
    url(r'^licencas/edita_licencas/(?P<pk>\d+)$', LicencasUpdate.as_view(), name='licencas_update'),
    url(r'^licencas/remove_licencas/(?P<pk>\d+)$', LicencasDelete.as_view(), name='licencas_delete'),
    url(r'^licencas/detalha_licencas/(?P<pk>\d+)$', LicencasDetail.as_view(), name='licencas_detail'),

    url(r'^lista_historico_pagamentos/$', Historico_PagamentosList.as_view(), name='historicoPagamento_list')
)

Web/cardapio/models.py
from django.db import models
import datetime
from django.utils import timezone
from clientes.models import Cliente, Endereco

# Create your models here.

class Produto(models.Model):
    def __unicode__(self): 
        return self.nome
    nome = models.CharField(max_length=200, unique=True)
    preco = models.DecimalField(max_digits=7 , decimal_places=2)
    isPizza = models.BooleanField()

class Ingrediente(models.Model):
    def __unicode__(self):
        return self.nome
    nome = models.CharField(max_length=200, unique=True)
    marca = models.CharField(max_length=100)
    descricao = models.CharField(max_length=300, default="-")

class Pizza(models.Model):
    def __unicode__(self):
        return self.produto.nome
    produto = models.ForeignKey(Produto)
    GRANDE = 'G'
    MEDIA = 'M'
    PEQUENA = 'P'
    TAMANHO_CHOICES = (
        (GRANDE, 'Grande'),
        (MEDIA, 'Media'),
        (PEQUENA, 'Pequena'),
    )
    tamanho = models.CharField(max_length=1, choices=TAMANHO_CHOICES)
    tipoDePizza = models.CharField(max_length=200)
    ingredientes = models.ManyToManyField(Ingrediente, through='PizzaIngrediente')

class Bebida(models.Model):
    def __unicode__(self):
        return self.produto.nome
    produto = models.ForeignKey(Produto)

class PizzaIngrediente(models.Model):
    def __unicode__(self): 
        return u'%s %s' % (self.pizza.produto.nome, self.ingrediente.nome)
    pizza = models.ForeignKey(Pizza)
    ingrediente = models.ForeignKey(Ingrediente)
    quantidadeDeUso = models.DecimalField(max_digits=7, decimal_places=3)
    KILOGRAMA = 'KG'
    PITADA = 'PT'
    XICARA = 'XC'
    COLHER = 'CL'
    MEDIDA_CHOICES = (
        (KILOGRAMA, 'Kilograma'),
        (PITADA, 'Pitada'),
        (XICARA, 'Xicara'),
        (COLHER, 'Colher'),
    )
    medida = models.CharField(max_length=2, choices=MEDIDA_CHOICES)
    isRecheio = models.BooleanField(default=True)



class Pedido(models.Model):
    def __unicode__(self): 
        return self.cliente.nome
    status = models.CharField(max_length=100)
    cliente = models.ForeignKey(Cliente) 
    endereco = models.ForeignKey(Endereco) 
    telefone = models.CharField(max_length=100)
    isdelivery = models.BooleanField()
    data = models.DateField(auto_now_add=True)

class Item(models.Model):
    def __unicode__(self):
        return u'%s %s' % (self.quantidade, self.produto.nome)
    produto = models.ForeignKey(Produto)
    pedido = models.ForeignKey(Pedido)
    quantidade = models.DecimalField(max_digits=7 , decimal_places=2)
    UM = 'UM'
    DOIS = 'DO'
    TRES = 'TR'
    AGRUPAMENTO_CHOICES = (
        (UM, 'Um'),
        (DOIS, 'Dois'),
        (TRES, 'Tres'),
    )
    agrupamento = models.CharField(max_length=2, choices=AGRUPAMENTO_CHOICES)
    preco = models.DecimalField(max_digits=7 , decimal_places=2)
    promocao = models.BooleanField()
    observacao = models.CharField(max_length=400)
    
class PromocoesDaPizzaria(models.Model):
    def __unicode__(self): 
        return self.nome
    nome = models.CharField(max_length=100)
    item = models.ForeignKey(Item)
    itemExtra = models.ForeignKey(Produto)
    dataInicio = models.DateField()
    dataTermino = models.DateField()

class Pagamento(models.Model):
    def __unicode__(self): 
        return self.valorTotal
    pedido = models.ForeignKey(Pedido) 
    metodoPagamento = models.CharField(max_length=100)
    valorTotal = models.DecimalField(max_digits=7 , decimal_places=2)
    precisaTroco = models.BooleanField()
    promocao = models.ForeignKey(PromocoesDaPizzaria)
    status = models.BooleanField()

Web/cardapio/templates/bebida.html
{% extends "base.html" %}
{% load extra_order %}
	{% block content %}
	<div class="row">
            <div class="col-md-12">
               <!-- BEGIN PAGE TITLE & BREADCRUMB-->
               <h3 class="page-title">
                  Bebida <small>nova</small>
               </h3>
               <ul class="page-breadcrumb breadcrumb">
                  <li>
                     <i class="icon-home"></i>
                     <a href="/">Home</a> 
                     <i class="icon-angle-right"></i>
                  </li>
                  <li>
                     <a href="/cardapio/bebida">Bebidas</a>
                     <i class="icon-angle-right"></i>
                  </li>
               </ul>
               <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
         </div>
			<div class="tab-content">
				<h4>Cadastrar Bebida</h4>
		    	<a type="button" href="{% url 'bebidaNova' %}" class="btn btn-lg btn-success btn-add">
		    	<span class="glyphicon glyphicon-plus"></span>
		    	</a>
			 	<div class="portlet box">
					<h4>Consultar Bebida</h4>

						<div class="portlet-body form">
				      		<form method="post" action="{% url 'bebidaConsulta' %}">
				        		{% csrf_token %}
				        	<div class="form-body">
			        			<div class="form-group">
				        			<div class="col-md-4 fluid" style="padding-top:20px">	
				        				<input type="text" id="nome" name="nome" class="form-control"/>
				        			</div>
				        			<div class="form-actions fluid">
				                    	<button type="submit" class="btn red">Consultar</button>
				                	</div>
				                </div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endblock %}

Web/cardapio/templates/bebidaAltera.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Altera Bebida
    {% endblock %}

    {% block content %}
<h1>{{ bebida.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'bebidaDeletar' bebida.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1> 
    <h4>Preço:</h4> 
    <div class="form">
      <form method="post" action="{% url 'bebidaEdita' bebida.id %}">
        {% csrf_token%}
        <ul>
          <li>
            <input type="number" name="preco" step="0.01" min ="0"/>
            <input type="submit" value="Alterar"/>
          </li>
        </ul>
    </div> 
    {% endblock %}

Web/cardapio/templates/bebidaNova.html
{% extends "base.html" %}
{% load extra_order %}
	{% block content %}
	<div class="row">
            <div class="col-md-12">
               <!-- BEGIN PAGE TITLE & BREADCRUMB-->
               <h3 class="page-title">
                  Bebida <small>nova</small>
               </h3>
               <ul class="page-breadcrumb breadcrumb">
                  <li>
                     <i class="icon-home"></i>
                     <a href="/">Home</a> 
                     <i class="icon-angle-right"></i>
                  </li>
                  <li>
                     <a href="/cardapio/bebida">Cardapio</a>
                     <i class="icon-angle-right"></i>
                  </li>
                  <li><a href="#">Cadastrar Bebida</a></li>
               </ul>
               <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
         </div>
         <div class="tab-content">
			<div class="portlet box red">
				<div class="portlet-title">
					<div class="caption">
						Cadastrar Bebida
					</div>
				</div> 
				<div class="portlet-body form">
					<form method="post" action="{% url 'bebidaCadastrar' %}" class="form-horizontal">
					{% csrf_token%}
						<div class="form-group">
							<label class="col-md-3 control-label">
								Nome
							</label>
							<div class="col-md-4">
								<input type="text" name="nome" value="" class="form-control"/> 
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-3 control-label">Preço:</label>
							<div class="col-md-4">	
								<input type="number" name="preco" step="0.01" min ="0" value="" class="form-control"/> 
							</div>
						</div>		
						<div class="form-actions fluid">
                         	<div class="col-md-offset-3 col-md-9">
                             		<button type="submit" class="btn red">Cadastrar</button>                              
                        	</div>
	                    </div>
					</form>
				</div>
			</div>
		</div>
		{% endblock %}

Web/cardapio/templates/indexCardapio.html
{% extends "index.html" %}
{% load staticfiles %}


{% block navbar_links %}
<li class="active"><a href="#">Principal</a></li>
<li><a href="#">Pedido</a></li>
<li><a href="#">BI</a></li>
<li><a href="#">Marketing/Feedback</a></li>
{% endblock %}

{% block sidebar %}
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
      	{% block sidebar_links %}
	        <li><a href="{% url 'pizza' %}">Pizza</a></li>
	        <li><a href="{% url 'bebida' %}">Bebida</a></li>
	        <li><a href="{% url 'ingrediente' %}">Ingrediente</a></li>
        {% endblock %}
      </ul>
    </div>
{% endblock %}

{% block content %}
{% comment %}<h1 class="page-header">Bem Vindo</h1>{% endcomment %}
<div class="jumbotron">
	<h1 class="text-center">CooPizza</h1>
	<p class="lead text-justify"> Melhor ERP para pizzarias.</p>
</div>
{% endblock %}

Web/cardapio/templates/ingrediente.html
{% extends "base.html" %}
{% load extra_order %}
	{% block content %}
	<div class="row">
            <div class="col-md-12">
               <!-- BEGIN PAGE TITLE & BREADCRUMB-->
               <h3 class="page-title">
                  Ingrediente <small>novo</small>
               </h3>
               <ul class="page-breadcrumb breadcrumb">
                  <li>
                     <i class="icon-home"></i>
                     <a href="/">Home</a> 
                     <i class="icon-angle-right"></i>
                  </li>
                  <li>
                     <a href="/cardapio/ingrediente">Ingrediente</a>
                     <i class="icon-angle-right"></i>
                  </li>
               </ul>
               <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
         </div>
			<div class="tab-content">
				<h4>Cadastrar Ingrediente</h4>
			    <!-- add -->
			    <a type="button" href="{% url 'ingredienteNovo' %}" class="btn btn-lg btn-success btn-add">
			    	<span class="glyphicon glyphicon-plus"></span>
			    </a>
			</div>
			<div class="portlet box">
		<h1>Consultar Ingrediente</h1>
		<div class="portlet-body form">
      		<form method="post" action="{% url 'ingredienteConsulta' %}">
        		{% csrf_token %}
        		<div class="col-md-4 fluid" style="padding-top:20px">	
        			<input type="text" id="nome" name="nome" class="form-control" />
        		</div>
      			<div class="form-actions fluid">
                    <button type="submit" class="btn red">Consultar</button>
                </div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

Web/cardapio/templates/ingredienteAltera.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Ingrediente {{pizza.nome}}
    {% endblock %}

    {% block content %}
<h1>Ingrediente {{ ingrediente.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'ingredienteDeletar' ingrediente.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Marca: {{ingrediente.marca}} </h4> 
    <h4>Descrição:</h4> R$ {{ingrediente.descricao}} 
    {% endblock %}

Web/cardapio/templates/pizzaAltera.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Altera Pizza
    {% endblock %}

    {% block content %}
<h1>Pizza {{ pizza.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletar' pizza.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Tamanho {{pizza.tamanho}} </h4> 
    <h4>Preço:</h4> 
    <div class="form">
      <form method="post" action="{% url 'pizzaEdita' pizza.id %}">
        {% csrf_token%}
        <ul>
          <li>
            <input type="number" name="preco" step="0.01" min ="0"/>
            <input type="submit" value="Alterar"/>
          </li>
        </ul>
    </div> 
    <h1> Composição da Pizza - Recheios </h1>
    <ul>
{% for pizzaingrediente in pizza.pizzaingrediente_set.all %}
      <li> {{ pizzaingrediente.ingrediente }} - {{ pizzaingrediente.quantidadeDeUso }} -- {{ pizzaingrediente.medida }} -- {{ pizzaingrediente.isRecheio }}
        <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletarIngrediente' pizza.id pizzaingrediente.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
{% endfor %}
    </ul>
    <a type="button" href="{% url 'pizzaIngrediente' pizza.id %}" class="btn btn-small btn-success btn-add">
                Adicionar ingrediente à pizza
            </a>
    <br>
    <br>
    <a type="button" href="http://gnt.globo.com/receitas/Conversor-de-medidas-para-receitas.shtml" class="btn btn-small btn-success btn-add" target="_blank">
                Auxílio para conversão de medidas
            </a>
    {% endblock %}

Web/cardapio/templates/pizzaDados.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Pizza {{pizza.produto.nome}}
    {% endblock %}

    {% block content %}
<h1>Pizza {{ pizza.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletar' pizza.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Tamanho {{pizza.tamanho}} </h4> 
    <h4>Preço:</h4> R$ {{pizza.produto.preco}} 
        <a type="button" class="btn btn-small btn-primary" href="{% url 'pizzaAltera' pizza.id %}">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
    <h1> Composição da Pizza - Recheios </h1>
    <ul>
{% for pizzaingrediente in pizza.pizzaingrediente_set.all %}
      <li> {{ pizzaingrediente.ingrediente }} - {{ pizzaingrediente.quantidadeDeUso }} -- {{ pizzaingrediente.medida }} -- {{ pizzaingrediente.isRecheio }}
        <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletarIngrediente' pizza.id pizzaingrediente.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
{% endfor %}
    </ul>
    <a type="button" href="{% url 'pizzaIngrediente' pizza.id %}" class="btn btn-small btn-success btn-add">
                Adicionar ingrediente à pizza
            </a>
    <br>
    <br>
    <a type="button" href="http://gnt.globo.com/receitas/Conversor-de-medidas-para-receitas.shtml" class="btn btn-small btn-success btn-add" target="_blank">
                Auxílio para conversão de medidas
            </a>
    {% endblock %}

Web/cardapio/templates/pizzaIngrediente.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Pizza {{pizza.produto.nome}}
    {% endblock %}

    {% block content %}
<h1>Pizza {{ pizza.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletar' pizza.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Tamanho {{pizza.tamanho}} </h4> 
    <h4>Preço:</h4> R$ {{pizza.produto.preco}} 
        <a type="button" class="btn btn-small btn-primary" href="{% url 'pizzaAltera' pizza.id %}">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
    <h1> Composição da Pizza - Recheios </h1>
    <ul>
{% for pizzaingrediente in pizza.pizzaingrediente_set.all %}
      <li> {{ pizzaingrediente.ingrediente }} - {{ pizzaingrediente.quantidadeDeUso }} -- {{ pizzaingrediente.medida }} -- {{ pizzaingrediente.isRecheio }}
        <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletarIngrediente' pizza.id pizzaingrediente.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
{% endfor %}
    </ul>
    <div class="form">
      <form method="post" action="adicionar">
        {% csrf_token%}
        <ul>
          <li>
            <label>Ingrediente:</label>
            <select name="nome">
                {% for ingrediente in ingredientes %}
                  <option value="{{ ingrediente.nome }}">{{ ingrediente.nome }}</option>  
                {% endfor %}
            </select>
          </li>
          <li>
            <label>Quantidade de uso padrão:</label>
            <input type="number" name="quantidadeDeUso" step="0.001" min ="0"/>
          </li>
          <li>
            <label>Tipo de medida:</label>
            <select name="medida"/>
            <option value="KG">KiloGrama</option>
            <option value="PT">Pitada</option>
            <option value="XC">Xicara</option>
            <option value="CL">Colher</option>
          </select>
          </li>
          <li>
            <label>É recheio?</label>
            <input type="checkbox" name="isRecheio"/>
          </li>
            <input type="submit" value="Adicionar"/>
        </ul>
    </div> 
    <br>
    <br>
    <a type="button" href="http://gnt.globo.com/receitas/Conversor-de-medidas-para-receitas.shtml" class="btn btn-small btn-success btn-add" target="_blank">
                Auxílio para conversão de medidas
            </a>
    {% endblock %}